"""empty message

Revision ID: fd7a351b3471
Revises: 
Create Date: 2020-09-07 19:42:43.361215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7a351b3471'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=50), nullable=False),
    sa.Column('kategorie_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=9999), nullable=True),
    sa.ForeignKeyConstraint(['kategorie_id'], ['kategorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    op.drop_table('kategorie')
    # ### end Alembic commands ###
